### ISSUE TITLE
Please add CxSAST scans for main branch and PRs

### ISSUE THREAD

**Issue by kaplanlior** [Checkmarx/sast-to-ast-export#24]
Similar to KICS, lets make sure the code in this repo is scanned with CxSAST.

**Comment by constantinoantunes1** [comment]
This repo is already being scanned by CxSAST.
For example: https://github.com/Checkmarx/sast-to-ast-export/pull/18
![image](https://user-images.githubusercontent.com/78747816/152186148-7cbb2dbe-4b72-47ab-bd33-7ab726cf4722.png)
